model:
  type: "mediapipe"
  name: "pose_landmarker_heavy.task"
  device: "cpu"

paths:
  input: "./data/input/outdoor"
  output: "./data/output/mediapipe/pose_data"
  models: "./data/models/mediapipe"